# Generated manually for demo project
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Department', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=255)),('head_name', models.CharField(blank=True, max_length=255)),('institute', models.CharField(blank=True, max_length=255))]),
        migrations.CreateModel(name='StudyGroup', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('number', models.CharField(max_length=32, unique=True)),('speciality', models.CharField(blank=True, max_length=64)),('curator', models.CharField(blank=True, max_length=255)),('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.department'))]),
        migrations.CreateModel(name='Person', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('full_name', models.CharField(max_length=255)),('role', models.CharField(choices=[('student','Студент'),('teacher','Преподаватель'),('dean','Деканат')], max_length=20)),('login', models.CharField(max_length=80, unique=True)),('password', models.CharField(default='1234', max_length=80)),('position', models.CharField(blank=True, max_length=120)),('is_monitor', models.BooleanField(default=False)),('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='core.department')),('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studygroup'))]),
        migrations.CreateModel(name='Subject', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('title', models.CharField(max_length=255, unique=True)),('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department'))]),
        migrations.CreateModel(name='Lesson', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('day_of_week', models.IntegerField(choices=[(0,'Понедельник'),(1,'Вторник'),(2,'Среда'),(3,'Четверг'),(4,'Пятница'),(5,'Суббота')])),('time', models.CharField(max_length=20)),('week_type', models.CharField(choices=[('v','Верхняя'),('n','Нижняя'),('both','Каждую неделю')], max_length=10)),('building', models.CharField(blank=True, max_length=80)),('room', models.CharField(blank=True, max_length=80)),('lesson_type', models.CharField(blank=True, max_length=40)),('subgroup', models.CharField(blank=True, max_length=40)),('note', models.CharField(blank=True, max_length=255)),('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.studygroup')),('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject')),('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.person'))]),
        migrations.CreateModel(name='Attendance', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('status', models.CharField(choices=[('present','+'),('absent','-')], max_length=20)),('reason', models.CharField(blank=True, max_length=255)),('updated_at', models.DateTimeField(auto_now=True)),('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.lesson')),('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='core.person')),('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.person'))], options={'unique_together': {('student','lesson','date')}}),
    ]
